from .customer import *
from .admin import *
from .mechanic import *
from .auth import *
from .car import *
from .car_class import *
from .customer_car import *
from .manufacturer import *
from .fuel_type import *
from .address import *
from .area import *
from .price_chart import *
from .service_category import *
from .service_reviews import *
from .service import *
from .assignment_type import *
from .status import *
from .timeslot import *
from .bookings import *
from .content import *
from .gst import *
from .query import *
