"""Booking payment status update

Revision ID: 0a6018a776ff
Revises: 6d9240cd0d82
Create Date: 2025-11-08 01:42:05.476260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6018a776ff'
down_revision: Union[str, Sequence[str], None] = '6d9240cd0d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'payment_methods', ['payment_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'payment_method_id')
    # ### end Alembic commands ###
