"""customer car model update2

Revision ID: 1053b8e1a5b4
Revises: 4bbaeb138292
Create Date: 2025-11-02 00:38:53.145218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1053b8e1a5b4'
down_revision: Union[str, Sequence[str], None] = '4bbaeb138292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer_cars', ['reg_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_cars', type_='unique')
    # ### end Alembic commands ###
