"""test1

Revision ID: 1672eb02cfb3
Revises: 26d5a4fb0141
Create Date: 2025-10-29 12:25:01.224492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1672eb02cfb3'
down_revision: Union[str, Sequence[str], None] = '26d5a4fb0141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customers_phone_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'users', ['phone'], ['phone'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_phone_fkey'), 'customers', 'users', ['phone'], ['phone'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
