"""add note field in assignment

Revision ID: 19a2a6209c2d
Revises: 41b1c281f843
Create Date: 2025-11-08 20:14:04.801167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a2a6209c2d'
down_revision: Union[str, Sequence[str], None] = '41b1c281f843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_assignment', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # 2️⃣ Backfill existing rows so they have empty arrays instead of NULL
    op.execute("UPDATE booking_progress SET completed_service_ids = '{}' WHERE completed_service_ids IS NULL")

    # 3️⃣ Make the column NOT NULL
    op.alter_column('booking_progress', 'completed_service_ids', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_assignment', 'note')
    # ### end Alembic commands ###
