"""Booking progress - service ids update

Revision ID: 41b1c281f843
Revises: 0a6018a776ff
Create Date: 2025-11-08 20:01:02.040677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b1c281f843'
down_revision: Union[str, Sequence[str], None] = '0a6018a776ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_progress', sa.Column('completed_service_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('mechanics', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mechanics', 'score')
    op.drop_column('booking_progress', 'completed_service_ids')
    # ### end Alembic commands ###
