"""customer car model update

Revision ID: 4bbaeb138292
Revises: 9475a80c8d7e
Create Date: 2025-11-02 00:37:31.353188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbaeb138292'
down_revision: Union[str, Sequence[str], None] = '9475a80c8d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_cars', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('customer_cars', sa.Column('car_model_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('customer_cars_car_id_fkey'), 'customer_cars', type_='foreignkey')
    op.create_foreign_key(None, 'customer_cars', 'cars', ['car_model_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('customer_cars', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_cars', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_cars', type_='foreignkey')
    op.create_foreign_key(op.f('customer_cars_car_id_fkey'), 'customer_cars', 'cars', ['car_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('customer_cars', 'car_model_id')
    op.drop_column('customer_cars', 'id')
    # ### end Alembic commands ###
