"""check

Revision ID: 7d0f8babdbad
Revises: 1053b8e1a5b4
Create Date: 2025-11-03 13:38:23.850568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0f8babdbad'
down_revision: Union[str, Sequence[str], None] = '1053b8e1a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cars', 'fuel_types', ['fuel_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'service_reviews', 'services', ['service_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_reviews', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    # ### end Alembic commands ###
