"""timeslot data type update

Revision ID: 7e985f046bdf
Revises: e83393593e16
Create Date: 2025-11-04 20:06:14.478454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e985f046bdf'
down_revision: Union[str, Sequence[str], None] = 'e83393593e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart', 'services', ['service_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'favourites', 'services', ['service_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'service_reviews', 'services', ['service_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('timeslots', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIME(),
               existing_nullable=False)
    op.alter_column('timeslots', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeslots', 'end_time',
               existing_type=sa.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('timeslots', 'start_time',
               existing_type=sa.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'service_reviews', type_='foreignkey')
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    # ### end Alembic commands ###
