"""made the changed field non-nullable

Revision ID: cc4da35de07f
Revises: 19a2a6209c2d
Create Date: 2025-11-08 20:19:57.571678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc4da35de07f'
down_revision: Union[str, Sequence[str], None] = '19a2a6209c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_progress', 'completed_service_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    op.alter_column('mechanics', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanics', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking_progress', 'completed_service_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    # ### end Alembic commands ###
