"""refund

Revision ID: e3346db18d90
Revises: cc4da35de07f
Create Date: 2025-11-09 02:37:41.754206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3346db18d90'
down_revision: Union[str, Sequence[str], None] = 'cc4da35de07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'offline_payments', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offline_payments', type_='unique')
    # ### end Alembic commands ###
