"""area pincode update

Revision ID: e83393593e16
Revises: 7d0f8babdbad
Create Date: 2025-11-04 14:27:49.039088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83393593e16'
down_revision: Union[str, Sequence[str], None] = '7d0f8babdbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('works', sa.ARRAY(sa.VARCHAR()), nullable=False),
    sa.Column('warranty_kms', sa.Integer(), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('time_hrs', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('difficulty', sa.SMALLINT(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.VARCHAR()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_chart',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('car_class_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['car_class_id'], ['car_classes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'car_class_id')
    )
    op.create_table('service_fuel_types',
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('line1', sa.VARCHAR(), nullable=False),
    sa.Column('line2', sa.VARCHAR(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('customer_id', sa.VARCHAR(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'service_id')
    )
    op.create_table('favourites',
    sa.Column('customer_id', sa.VARCHAR(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'service_id')
    )
    op.create_table('service_reviews',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.SMALLINT(), nullable=False),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.VARCHAR()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'customer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_reviews')
    op.drop_table('favourites')
    op.drop_table('cart')
    op.drop_table('addresses')
    op.drop_table('service_fuel_types')
    op.drop_table('price_chart')
    op.drop_table('services')
    op.drop_table('areas')
    # ### end Alembic commands ###
