"""check

Revision ID: fa030e1699f9
Revises: 7e985f046bdf
Create Date: 2025-11-04 23:07:03.038150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa030e1699f9'
down_revision: Union[str, Sequence[str], None] = '7e985f046bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanics',
    sa.Column('id', sa.VARCHAR(), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.BIGINT(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('pickup_drop', sa.Boolean(), nullable=True),
    sa.Column('analysis', sa.Boolean(), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['phone'], ['users.phone'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanics_phone'), 'mechanics', ['phone'], unique=True)
    op.create_foreign_key(None, 'mechanic_service_categories', 'mechanics', ['mechanic_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mechanic_service_categories', type_='foreignkey')
    op.drop_index(op.f('ix_mechanics_phone'), table_name='mechanics')
    op.drop_table('mechanics')
    # ### end Alembic commands ###
